apiVersion: apps/v1
kind: Deployment
metadata: 
  name: news
spec:
  selector:
    matchLabels:
      app: news
  replicas: 1
  template: #template for the pods
    metadata:
      labels:
        app: news
    spec:
      containers: 
      - name: ms-news
        image: mysql/mysql-server:8.0.23

---
apiVersion: v1
kind: Pod
metadata: 
  name: ms-news
  labels:
    app: news

spec:
  containers: 
  - name: ms-news
    image: alpine:latest