version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"
  oracledb:
    image: store/oracle/database-enterprise:12.2.0.1
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD=tele123