server:
  port: 8080

logging:
  level:
    ROOT: WARN
    com.gamingbaku.user: DEBUG

spring:
  application:
    name: ms-news
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      ddl-auto: create #it will be validate, for now on the purpose of test it is create
    open-in-view: false
  liquibase:
    change-log: classpath:config/liquibase/db.master-changelog.xml
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orclpdb
    username: hr
    password: hr
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      pool-name: NewsHikariPool
      auto-commit: false
      connection-timeout: 10000
      connection-test-query: SELECT 1 FROM dual
      idle-timeout: 60000
      max-lifetime: 120000