server:
  port: 8080

logging:
  level:
    ROOT: WARN
    com.gamingbaku.user: DEBUG

spring:
  application:
    name: ms-news
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      ddl-auto: create #it will be validate, for now on the purpose of test it is create
    open-in-view: false
  liquibase:
    change-log: classpath:config/liquibase/db.master-changelog.xml
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orclpdb
    username: hr
    password: hr1
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      pool-name: NewsHikariPool
      auto-commit: false
      connection-timeout: 10000
      connection-test-query: SELECT 1 FROM dual
      idle-timeout: 60000
      max-lifetime: 120000

news:
  initial-limit: 10
  max-limit: 20
  default-offset: 0

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka"
    fetch-registry: true
    register-with-eureka: true

# if you call this application with feign or restTemplate, instead of using
# localhost:8081/content/upload, just use ms-news/content/upload.
# eureka maintains this for us. REMEMBER!!!

# when using feign, for handling load balancing, examine and use @LoadBalanced annotation