spring:
  application:
    name: ms-content
  messages:
    basename: i18n/messages
    encoding: UTF-8
  minio:
    access-key: hope
    secret-key: pr0ject-hope
    url: http://127.0.0.1:9000
    bucket: news
    expiry-time: 3600 #1 hour
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8084